// eslint-disable-next-line filenames/match-regex
module.exports = {
  apps: [
    {
      name: 'agile-node_service',
      script: './server.js',
      instances: 1,
      autorestart: true,
      env_production: {
        NODE_ENV: 'production',
        PORT: 2103,
        DB_NAME: '',
        DB_USER_NAME: '',
        DB_PASSWORD: '',
        DB_PORT: 3306,
        DB_HOST: '',
        HOST: '0.0.0.0',
        AWS_ACCESS_KEY_ID: '',
        AWS_SECRET_ACCESS_KEY: '',
        AWS_REGION: '',
        S3_BUCKET_NAME: '',
        SQS_DLQ_URL: '',
        SQS_MAIN_QUEUE_URL: '',
      },
      env_pm2: {
        NODE_ENV: 'pm2',
        PORT: 2103,
        AWS_ACCESS_KEY_ID: '',
        AWS_SECRET_ACCESS_KEY: '',
        AWS_REGION: '',
        S3_BUCKET_NAME: '',
        SQS_DLQ_URL: '',
        SQS_MAIN_QUEUE_URL: '',
      },
      env_development: {
        NODE_ENV: 'development',
        PORT: 2103,
        DB_USER_NAME: '',
        DB_PASSWORD: '',
        DB_NAME: '',
        DB_PORT: 3306,
        DB_HOST: '',
        HOST: '0.0.0.0',
        AWS_ACCESS_KEY_ID: '',
        AWS_SECRET_ACCESS_KEY: '',
        AWS_REGION: '',
        S3_BUCKET_NAME: '',
        SQS_DLQ_URL: '',
        SQS_MAIN_QUEUE_URL: '',
      },
      env_local: {
        NODE_ENV: 'local',
        PORT: 2103,
        DB_USER_NAME: '',
        DB_PASSWORD: '',
        DB_NAME: '',
        DB_PORT: 3306,
        DB_HOST: '',
        HOST: '0.0.0.0',
        AWS_ACCESS_KEY_ID: '',
        AWS_SECRET_ACCESS_KEY: '',
        AWS_REGION: '',
        S3_BUCKET_NAME: '',
        SQS_DLQ_URL: '',
        SQS_MAIN_QUEUE_URL: '',
      },
    },
  ],
};
